imports:
    - { resource: tables.yml }

services:
    phpbb.boardrules.admin.controller:
        class: phpbb\boardrules\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template

    phpbb.boardrules.controller:
        class: phpbb\boardrules\controller\main_controller
        arguments:
            - @config
            - @controller.helper
            - @phpbb.boardrules.operator
            - @template
            - @user
            - %tables.boardrules%

    phpbb.boardrules.entity:
        class: phpbb\boardrules\entity\rule
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %tables.boardrules%

    phpbb.boardrules.listener:
        class: phpbb\boardrules\event\listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
